### ISSUE TITLE
Carbon_aware_advisor_model

### ISSUE THREAD

**Issue by jimbou** [Green-Software-Foundation/hack#111]
### Prize category

Best Plugin

### Overview

Overview
The CarbonAwareAdvisor model is designed to provide carbon emission data based on specified locations and timeframes. It interacts with the Carbon Aware SDK to fetch the most carbon-efficient options for given parameters.

Key Features
Location Filtering: Users can specify a list of locations to consider for carbon emission data.
Timeframe Filtering: Users can define time ranges to narrow down the search for carbon emission data.
Sampling: An optional parameter that allows users to specify the number of data points to sample from the available data, providing a broader view of the carbon emission landscape. If sampling is not defined in the impl then no data points are sampled and the plotted-points is not added in the ompl.
Outputs
** Suggestions: **: List of the best location and time combination to minimize the carbon score along with that score.
** Plotted-points: **: ONLY IF THE SAMPLING PARAMETER IS INITIALIZED IN THE IMPL. A sampling number of samples for trade-off visualization. A best combination from each timeframe is always included . So sampling must be >= number of time regions in the allowed-timeframes. The plotter model can then be used in the pipeline to plot this samples.

### Have you got a project team yet?

Yes and we aren't recruiting

### Project team

@jimbou
@TomasKopunec
@JasonLuuk
@TelmaGudmunds

### Terms of Participation

- [X] I agree to the hackathon [Rules & Terms](https://github.com/Green-Software-Foundation/hack/wiki/Rules-and-Terms) and [Code of Conduct](https://github.com/Green-Software-Foundation/hack/wiki/Code-of-Conduct)

**Comment by rachanakabi** [comment]
I am interested in this job.

**Comment by russelltrow** [comment]
This project has been merged into https://github.com/Green-Software-Foundation/hack/issues/123
