### ISSUE TITLE
Plotter_model

### ISSUE THREAD

**Issue by jimbou** [Green-Software-Foundation/hack#112]
### Prize category

Best Plugin

### Overview

The Plotter model created for the Impact Engine Framework is designed to visualize data through various types of graphs such as bar, line, and scatter plots. It takes input in YAML format or csv format , defining the x and y values along with additional parameters to customize the plots.

This model is typically used in a pipeline following data-enrichment models like carbon-aware-advisor, which populates the plotted-points parameter required by Plotter. If the user prefers he can specify the plotted-points parameter himself in the Impl file but the main value of the model is its ability to visualize the data provided by other models of the Impact Engine Framework. The user can also specify a csv file to read the data to plot from.

### Have you got a project team yet?

I am working on this project alone

### Project team

@jimbou

### Terms of Participation

- [X] I agree to the hackathon [Rules & Terms](https://github.com/Green-Software-Foundation/hack/wiki/Rules-and-Terms) and [Code of Conduct](https://github.com/Green-Software-Foundation/hack/wiki/Code-of-Conduct)

**Comment by russelltrow** [comment]
This project has been merged into https://github.com/Green-Software-Foundation/hack/issues/123
