### ISSUE TITLE
Sustainable Logging Solution for Reduced Carbon Footprint Using IF

### ISSUE THREAD

**Issue by agwlprince617** [Green-Software-Foundation/hack#121]
### Prize category

Best Content

### Overview

Few systems adds TBs of log collected per day which are operationally not required and contribute to high carbon footprint.
We propose to use compressed logging mechanisms to achieve compression of logs without actually losing any data and integrate Impact Framework to give insights. 

So basically let's say we have 10 GB's of logs which contribute to 20 kg of CO2, now using some mechanisms and integrating IF, logs get reduced to 1 GB and we contribute to 2 kg of CO2. So there is a whopping 90 percent drop in carbon emissions. These insights will enforce user's to become more environmental centric if they can visualize the data using IF.

Our proposed solution offers a dual benefit of **reducing** **carbon** footprint and **operational** **costs** through the implementation of compressed logging mechanisms and intelligent analytics integration.

### Questions to be answered

1. Is there a plugin within IF to generate carbon footprint data for the amount of memory that is consumed.

### Have you got a project team yet?

Yes and we aren't recruiting

### Terms of Participation

- [X] I agree to the hackathon [Rules & Terms](https://github.com/Green-Software-Foundation/hack/wiki/Rules-and-Terms) and [Code of Conduct](https://github.com/Green-Software-Foundation/hack/wiki/Code-of-Conduct)

**Comment by russelltrow** [comment]
Project lead is Dhanush Guptha Midde @Dhanushguptha19

**Comment by jmcook1186** [comment]
Hi - sorry for not seeing your question sooner - there is a plugin called `e-mem` in the `if-plugins` repository that uses a coefficient to estimate the energy consumed by a system's memory usage. You could then pass the result to other plugins that turn energy into carbon.

**Comment by agwlprince617** [comment]
Thanks Joseph for the information.

**Comment by agwlprince617** [comment]
Hi team,

I want to edit this issue with a different title and overview and what I
actually want to do. Could you please help me or do i need to create a new
issue?

With Regards,
Prince Agrawal

**Comment by agwlprince617** [comment]
Closing this issue as not planned
