### ISSUE TITLE
undefined

### ISSUE THREAD

**Issue by kisstodd** [Green-Software-Foundation/hack#67]
undefined

**Comment by jmcook1186** [comment]
Hi @kisstodd , looks interesting, we're certainly interested to have projects that can use IF to account for e-waste. Can you give any more details about what you will actually build?

**Comment by updownip** [comment]
@jmcook1186 We're developing a repository of tools aimed at sustainable software development, with a focus on C#, Java, and Python. Our toolset, inspired and extended from the Impact Framework, will include features to combat code duplication, security vulnerabilities, code smells, and dependency issues. Additionally, we're providing a Visual Studio Code extension to ensure easy integration of these sustainability tools into the development process. By combining cutting-edge technology with the principles of the Impact Framework, we're making sustainability a core aspect of software development.

**Comment by kisstodd** [comment]
@jmcook1186 We're developing a repository of tools aimed at sustainable software development, with a focus on C#, Java, and Python. Our toolset, inspired and extended from the Impact Framework, will include features to combat code duplication, security vulnerabilities, code smells, and dependency issues. Additionally, we're providing a Visual Studio Code extension to ensure easy integration of these sustainability tools into the development process. By combining cutting-edge technology with the principles of the Impact Framework, we're making sustainability a core aspect of software development.

**Comment by ng-druid** [comment]
@russelltrow We believe this project best qualifies as beyond carbon.

**Comment by kisstodd** [comment]
@russelltrow We believe this project best qualifies as beyond carbon.

**Comment by kisstodd** [comment]
@jawache Are you able to change the label to beyond carbon instead of enhancement-project?

**Comment by jawache** [comment]
Sure @kisstodd , @russelltrow can you help action?
